name: Image python-ssh

on:
  push:
    branches: ['main']
    paths:
      - 'docker-images/python-ssh'
  workflow_dispatch:

jobs:

  build_base:
    uses: ./.github/workflows/docker-build-publish.yml
    secrets: inherit
    with:
      image: python-ssh
      tag: "3.10"
      platforms: linux/amd64,linux/arm64

  build_node21:
    uses: ./.github/workflows/docker-build-publish.yml
    needs: build_base
    secrets: inherit
    with:
      image: python-ssh
      tag: 3.10-node21
      platforms: linux/amd64,linux/arm64

  build_node21_ffmpeg:
    uses: ./.github/workflows/docker-build-publish.yml
    needs: build_node21
    secrets: inherit
    with:
      image: python-ssh
      tag: 3.10-node21-ffmpeg
      platforms: linux/amd64,linux/arm64

  build_node21_ffmpeg_uv0418:
    uses: ./.github/workflows/docker-build-publish.yml
    needs: build_node21_ffmpeg
    secrets: inherit
    with:
      image: python-ssh
      tag: 3.10-node21-ffmpeg-uv0.4.18
      platforms: linux/amd64,linux/arm64
