name: Build and Publish Single Image

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
        description: 'Name of the Docker image to build and publish'
      tag:
        type: string
        required: true
        description: 'Tag of the Docker image to build and publish'
      platforms:
        type: string
        required: false
        description: 'Platforms to build the Docker image for'
        default: 'linux/amd64'

jobs:
  build:
    name: Publish Docker image to Docker Hub and GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    env:
      DOCKERHUB_IMAGE: atomie/${{ inputs.image }}
      GHCR_IMAGE: ghcr.io/atomiechen/${{ inputs.image }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            ${{ env.DOCKERHUB_IMAGE }}
            ${{ env.GHCR_IMAGE }}

      - name: Build and push Docker image ${{ inputs.image }}:${{ inputs.tag }}
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./docker-images/${{ inputs.image }}/${{ inputs.tag }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_IMAGE }}:${{ inputs.tag }}
            ${{ env.GHCR_IMAGE }}:${{ inputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation for Docker Hub
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.DOCKERHUB_IMAGE }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation for GitHub Container Registry
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.GHCR_IMAGE }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
